### ISSUE TITLE
Use a bolder color for action buttons on KEA3 website

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/KEA3web#60]
Currently, the action buttons on the homepage (Submit, Input an Example, Upload Proteins List) are a faded blue color; initially, it had looked to me like these buttons were greyed out/unavailable due to their faded color. I suggest to make their color a bolder shade of blue, so that it's more apparent that these are usable, active buttons...

**Comment by maxim-k** [comment]
Fixed at 8eb053450e6e5f4d1707a768817c70b1f35457f9
