### ISSUE TITLE
For Networks outputs, display the name of the user-selected library

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/KEA3web#62]
When viewing the Networks tab of outputs on the KEA3 site, there is a drop-down list that allows users to Select A Library. This functionality appears to work, as the plots are updated when different library options are selected from the list.

However, once the user has selected a library from the drop-down list, there is no further indication on this Network results page that the particular library has been selected. This can be confusing, e.g. if the user forgets which of the libraries they have selected, especially since the drop-down list button reverts to displaying "Select a Library" as soon as an option has been selected. It would be helpful to add some banner or header that displays the name of the selected library above each plot, to improve clarity.

**Comment by maxim-k** [comment]
Fixed in 938dea2facd3e145c7496434ded3ec4d7f0330dc
