### ISSUE TITLE
Add to the FAQ a list of supported browsers

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/KEA3web#66]
Some of the KEA3 site's features don't work on all browsers (e.g. Clustergrammer has display & functionality issues in Firefox); I suggest to add an FAQ item to list the browsers supported by KEA3.

**Comment by maxim-k** [comment]
This issue and #65 #67 are on Clustergrammer side, and the broken functionality (predicting clusters) to me doesn't seem to be crucial.
